### ISSUE TITLE
número de tentativas

### ISSUE THREAD

**Issue by marcuxyz** [zumbipy/Dmanga#3]
https://github.com/zumbipy/Dmanga/blob/97d84f76ea2654cbf1cfa9740fc8510992f9154d/unionmangas.py#L51

Você passar o número de tentativas como algo estático, quem pegar seu código vai ter que ir na classe alterar, sendo assim você pode fazer desta forma:

```python
    def __pagina_soup(url, tentativas=1):
     ....
```

Dessa forma o default será 1, se ninguém passar por parâmetro.

**Comment by zumbipy** [comment]
esta parte do código foi removido na versão atual.
